#Add comments to S7CommPlus error codes
#@author Tom Dohrmann
#@category Adonis
#@keybinding 
#@menupath 
#@toolbar 


from ghidra.app.decompiler import DecompInterface, ClangFuncNameToken, ClangToken, ClangTokenGroup, ClangVariableToken
from ghidra.program.model.symbol import SourceType
from ghidra.program.model.listing import CodeUnit
from ghidra.app.cmd.comments import SetCommentCmd

# Source: https://sourceforge.net/p/s7commwireshark/code/HEAD/tree/trunk/src/s7comm_plus/packet-s7comm_plus.c
error_code_names = {}
error_code_names[-513] = "ConcurrentTransactionRunning"
error_code_names[-512] = "MultiESIncompatibleOtherESVersion"
error_code_names[-511] = "MultiESLimitExceeded"
error_code_names[-510] = "MultiESConflict"
error_code_names[-509] = "StreamingError"
error_code_names[-508] = "NotAllowedWithStreaming"
error_code_names[-507] = "NoSupportForTls"
error_code_names[-506] = "StoppingTlsFailed"
error_code_names[-505] = "StartTlsFailed"
error_code_names[-504] = "PasswordAlreadyUsed"
error_code_names[-503] = "SpaceSignOnly_Hash"
error_code_names[-502] = "Invalid_TypeInfo_Format"
error_code_names[-501] = "SystemLimitExceeded"
error_code_names[-408] = "TextLib_buffer_overflow"
error_code_names[-407] = "TextLib_currently_not_available"
error_code_names[-406] = "Invalid_search_mode"
error_code_names[-405] = "TextLib_DublicatedTextID"
error_code_names[-404] = "TextLib_No_List_Header"
error_code_names[-403] = "TextLib_Not_Initialized"
error_code_names[-402] = "TextLib_Inconsistent_Structure"
error_code_names[-401] = "Invalid_Compiler_Alignment"
error_code_names[-353] = "SslHandshake"
error_code_names[-352] = "SecurityDisconnect"
error_code_names[-351] = "IntegrityError"
error_code_names[-303] = "DsIncompletePreparation"
error_code_names[-302] = "DsTargetLostUnexpected"
error_code_names[-301] = "DsInconsistantContainer"
error_code_names[-300] = "DsNotInitialized"
error_code_names[-279] = "PlainStructureNeedsLittleEndianData"
error_code_names[-278] = "PlainStructureNeedsBigEndianData"
error_code_names[-277] = "PlainStructureNeedsNenaOffsets"
error_code_names[-276] = "PlainStructureNeedsClassicOffsets"
error_code_names[-275] = "NotAllowedForPersistentData"
error_code_names[-274] = "NoDataPtrAvailable"
error_code_names[-273] = "TypeInfoHierarchyOverflow"
error_code_names[-272] = "OffsetPublished"
error_code_names[-271] = "VariableIsObsolete"
error_code_names[-270] = "NotOms"
error_code_names[-269] = "StoreDefect"
error_code_names[-268] = "Invalid_thread_context"
error_code_names[-267] = "Object_has_been_deleted "
error_code_names[-266] = "StoreNotExisting"
error_code_names[-265] = "StoreTransactionNotRunning"
error_code_names[-264] = "StoreTransactionAlreadyRunning"
error_code_names[-263] = "InvalidState"
error_code_names[-262] = "DuplicateQualifierValue"
error_code_names[-261] = "CBT_Container_Needed"
error_code_names[-260] = "NotCreateableByTransaction"
error_code_names[-259] = "InvalidTransactionState"
error_code_names[-258] = "InvalidVersion"
error_code_names[-257] = "ValueConversionNotPossible"
error_code_names[-256] = "InvalidTypeInfoModificationTime"
error_code_names[-255] = "InvalidLID"
error_code_names[-254] = "TypeInfoNotSet"
error_code_names[-253] = "OnlyTypeInfoAllowed"
error_code_names[-252] = "TypeInfoInvalidStructureType"
error_code_names[-251] = "StructNotAsBlobAccessible"
error_code_names[-250] = "WSTRING_not_supported"
error_code_names[-249] = "ConsistencyAsyncCallFailed"
error_code_names[-248] = "AsyncCallFailed"
error_code_names[-247] = "CallbackMissing"
error_code_names[-246] = "NullPointer"
error_code_names[-245] = "enError_StoreRefusedByBl"
error_code_names[-244] = "enError_StoreIsBusy"
error_code_names[-243] = "enError_StoreHandlerNotFree"
error_code_names[-242] = "FileFindElement"
error_code_names[-241] = "FileInvalidFindState"
error_code_names[-240] = "StateInvalidCase"
error_code_names[-239] = "AsyncFileRunning"
error_code_names[-238] = "SourceFileNotExisting"
error_code_names[-237] = "StoreAlreadyExisting"
error_code_names[-236] = "StoreInvalidHandle"
error_code_names[-235] = "ValueMissing"
error_code_names[-234] = "SerializerReinitFailed"
error_code_names[-233] = "StoreBadIndex"
error_code_names[-232] = "StoreWrongFormat"
error_code_names[-231] = "StoreInactive"
error_code_names[-230] = "StoreForceStore"
error_code_names[-227] = "FileUnlinkError"
error_code_names[-226] = "FileWriteError"
error_code_names[-225] = "FileReadError"
error_code_names[-223] = "StoreHasTransactionLock"
error_code_names[-222] = "Start_timer_error"
error_code_names[-221] = "InvalidConsistencyID"
error_code_names[-220] = "NotInConsistency"
error_code_names[-219] = "FileInvalidAccess"
error_code_names[-218] = "DirectoryRemoveError"
error_code_names[-217] = "DirectoryAlreadyClosed"
error_code_names[-216] = "DirectoryAlreadyOpen"
error_code_names[-215] = "FileNotFound"
error_code_names[-214] = "MessageBlockInitError"
error_code_names[-213] = "AsyncFileInstanceInUseError"
error_code_names[-212] = "HasFileNameError"
error_code_names[-211] = "NoFileName"
error_code_names[-210] = "FileInnerError"
error_code_names[-209] = "DirectoryCreateError"
error_code_names[-208] = "DirectoryOpenError"
error_code_names[-207] = "DirectoryCloseError"
error_code_names[-206] = "DirectoryReadError"
error_code_names[-205] = "InvalidOpenMode"
error_code_names[-204] = "FileAlreadyClose"
error_code_names[-203] = "FileAlreadyOpen"
error_code_names[-202] = "FileCloseError"
error_code_names[-201] = "FileOpenError"
error_code_names[-168] = "Tree_read_locked"
error_code_names[-167] = "ObjectNotLocked"
error_code_names[-166] = "ChildAlreadyLockedForDeletion"
error_code_names[-165] = "ExclusiveLockedAgainstDeletion"
error_code_names[-164] = "LockForDeletion"
error_code_names[-163] = "LockingLoopOverflow"
error_code_names[-162] = "TreeLockedAgainstDeletion"
error_code_names[-161] = "WrongLockForDeletionObject"
error_code_names[-160] = "LockingCounterUnderflow"
error_code_names[-159] = "LockingCounterOverflow"
error_code_names[-158] = "CallbackInterfaceIsMissing"
error_code_names[-157] = "ChildLocked"
error_code_names[-156] = "LockingStrategyAlreadyInQueue"
error_code_names[-155] = "LockingStrategyNotInProgress"
error_code_names[-154] = "ExclusiveLocked"
error_code_names[-153] = "LockingStrategyNotFound"
error_code_names[-152] = "LockingStrategyAlreadyInProgress"
error_code_names[-151] = "WrongLockingStrategy"
error_code_names[-150] = "TreeWriteLocked"
error_code_names[-136] = "ServiceCommFormatDiffersFromStoreFormat"
error_code_names[-135] = "ServiceAborted"
error_code_names[-134] = "ServiceMultiESNotSupported"
error_code_names[-133] = "ServiceNotChangableInErrorState"
error_code_names[-132] = "ServiceSubscriptionIsNotRunning"
error_code_names[-131] = "ServiceSubscriptionPrepareSequenceError"
error_code_names[-130] = "ServiceUnknownComFormat"
error_code_names[-129] = "ServiceObjectSerializationError"
error_code_names[-128] = "ServiceTypeAlreadyExists"
error_code_names[-127] = "ServiceAsyncRMC_impossible"
error_code_names[-126] = "ServiceWrongArgumentFormat"
error_code_names[-125] = "ServiceWrongNrOfArguments"
error_code_names[-124] = "ServiceNotChangableInRun"
error_code_names[-123] = "ServiceRequestSerializationError"
error_code_names[-122] = "ServiceNotificationParsingError"
error_code_names[-121] = "ServiceObjectParsingError"
error_code_names[-120] = "ServiceRequestParsingError"
error_code_names[-119] = "ServiceUnknownRequest"
error_code_names[-117] = "ServicePendingRequestNotFound"
error_code_names[-116] = "ServiceUnexpectedStream"
error_code_names[-115] = "ServiceUnexpectedResponse"
error_code_names[-114] = "ServiceCanNotCreateRequest"
error_code_names[-113] = "ServiceTooManySessions"
error_code_names[-112] = "ServiceTooManyRequests"
error_code_names[-111] = "ServiceTimeout"
error_code_names[-110] = "ServiceNotOwner"
error_code_names[-109] = "ServiceNotConnected"
error_code_names[-108] = "ServiceNotAvailable"
error_code_names[-108] = "ServiceNotAvaliable"
error_code_names[-107] = "ServiceNotAllowed"
error_code_names[-106] = "ServiceInvalidSession"
error_code_names[-105] = "ServiceInvalidObject"
error_code_names[-104] = "ServiceInvalidAddress"
error_code_names[-103] = "ServiceFailedToDisconnect"
error_code_names[-102] = "ServiceDisconnected"
error_code_names[-101] = "ServiceActivateFailed"
error_code_names[-100] = "ServiceAccessDenied"
error_code_names[-99] = "PersistenceNotAvailable"
error_code_names[-98] = "NotPersistent"
error_code_names[-97] = "VariableWithQualifier"
error_code_names[-96] = "InvalidObjectWithQualifier"
error_code_names[-95] = "NotImplemented"
error_code_names[-94] = "ObjectIsNotPassive"
error_code_names[-93] = "ObjectAllreadyInTree"
error_code_names[-92] = "ObjectIsActive"
error_code_names[-91] = "ObjectIsPassive"
error_code_names[-90] = "ObjectIsMarkedForDeletetion"
error_code_names[-89] = "DataIsReferenced"
error_code_names[-88] = "InfoNotAvailable"
error_code_names[-87] = "OCBMissing"
error_code_names[-86] = "NoDeleteAllowed"
error_code_names[-85] = "StructOnlyInDetailsAccessible"
error_code_names[-84] = "ValueNotMoveable"
error_code_names[-82] = "OCBAlreadyUsed"
error_code_names[-81] = "AIDAlreadySet"
error_code_names[-80] = "DuplicateAID"
error_code_names[-79] = "NoProxyObjectAllowed"
error_code_names[-78] = "AllocatorNotFound"
error_code_names[-77] = "ObjectFactoryNotfound"
error_code_names[-76] = "CannotDeleteNativeObject"
error_code_names[-75] = "ValueTimeout"
error_code_names[-74] = "CompositionNotAllowed"
error_code_names[-73] = "AsyncButCallbackInterfaceNotFound"
error_code_names[-72] = "ElementIsTransistent"
error_code_names[-71] = "HierarchyOverflow"
error_code_names[-70] = "InvalidAssociation"
error_code_names[-69] = "QualifierNotSync"
error_code_names[-68] = "QualifierNotFound"
error_code_names[-67] = "InvalidRoot"
error_code_names[-66] = "HashIndexNotFound"
error_code_names[-65] = "IteratorInterfaceNotFound"
error_code_names[-64] = "ObjectAllreadyInAssociation"
error_code_names[-63] = "AssociationNotFound"
error_code_names[-62] = "AssociationNotQualified"
error_code_names[-61] = "InvalidValueRange"
error_code_names[-60] = "DuplicateRID"
error_code_names[-59] = "LinkInterfaceNotFound"
error_code_names[-58] = "AsyncOnly"
error_code_names[-57] = "VariableTypeNotAllowed"
error_code_names[-56] = "VariableIsSpecificOnly"
error_code_names[-55] = "InvalidComposition"
error_code_names[-54] = "NoFreeRID"
error_code_names[-53] = "BufferOverflow"
error_code_names[-52] = "DuplicateLink"
error_code_names[-51] = "ObjectIsLocked"
error_code_names[-50] = "ReadOnlyObject"
error_code_names[-49] = "StringMustHaveHexCharacters_only"
error_code_names[-48] = "LinkNotFound"
error_code_names[-47] = "InvalidMetaType"
error_code_names[-46] = "ObjectIsNotInstantiable"
error_code_names[-45] = "CannotCreateAbstractObject"
error_code_names[-44] = "NoSeparateLoadMemoryFileAllowed"
error_code_names[-43] = "CreateChildObjectWithinCreateChildObject"
error_code_names[-42] = "M_N_AssocNotSupported"
error_code_names[-41] = "ReadOnlyProperty"
error_code_names[-40] = "DirectoryNotFound"
error_code_names[-39] = "FilenameExcedRange"
error_code_names[-38] = "ClassNotAllowed"
error_code_names[-37] = "UnexpectedAttribute"
error_code_names[-36] = "NumericUnderflow"
error_code_names[-35] = "NumericOverflow"
error_code_names[-34] = "UnexpectedToken"
error_code_names[-33] = "BadCast"
error_code_names[-32] = "InvalidAID"
error_code_names[-30] = "InvalidRID"
error_code_names[-29] = "ObjectExistsWithSameID"
error_code_names[-28] = "UnexpectedFragType"
error_code_names[-27] = "UnexpectedEndTag"
error_code_names[-26] = "UnknownStartTag"
error_code_names[-25] = "InvalidTypeID"
error_code_names[-24] = "InvalidID"
error_code_names[-23] = "WritingDataError"
error_code_names[-22] = "NoMoreDataAvailable"
error_code_names[-21] = "ReadingDataError"
error_code_names[-20] = "StreamIsCurrentlyUsed"
error_code_names[-19] = "Invalid_namespace_ID"
error_code_names[-18] = "CanNotDeliver"
error_code_names[-17] = "InvalidCRC"
error_code_names[-16] = "DuplicateNameInCurrentHierarchy"
error_code_names[-15] = "ClassNotSupportedFromClassFactory"
error_code_names[-14] = "ClassNotFound"
error_code_names[-13] = "CardinalityOverflow"
error_code_names[-12] = "ObjectNotFound"
error_code_names[-11] = "InvalidFileHandle"
error_code_names[-10] = "InvalidDestinationReferenceType2"
error_code_names[-9] = "InvalidSourceReferenceType2"
error_code_names[-8] = "ReferencesAreNotConnected"
error_code_names[-7] = "InvalidDestinationReferenceType"
error_code_names[-6] = "InvalidSourceReferenceType"
error_code_names[-5] = "ErrorInSprintf"
error_code_names[-4] = "NotEnoughMemoryAvailable"
error_code_names[-3] = "InvalidArgumentValue"
error_code_names[-2] = "InvalidValueType"
error_code_names[-1] = "UnknownError"
error_code_names[0] = "OK"
error_code_names[1] = "MessageTypeCreated"
error_code_names[2] = "MessageLinkEnd"
error_code_names[3] = "MessageValueUnchanged"
error_code_names[4] = "MessageSetStructAttribute"
error_code_names[5] = "MessageResponseNeeded"
error_code_names[6] = "MessageAsyncCallPending"
error_code_names[7] = "MessageAssociationWrongSide"
error_code_names[8] = "MessageLockPending"
error_code_names[9] = "MessageAlreadyLocked"
error_code_names[10] = "WarningDefaultValue"
error_code_names[11] = "MessageCanMoveValue"
error_code_names[12] = "MessageLoadSucceeded"
error_code_names[13] = "MessageContentAlreadyMoved"
error_code_names[14] = "WarningStoreEmpty"
error_code_names[15] = "MessageValueSwapped"
error_code_names[16] = "MessageStoreActive"
error_code_names[17] = "MessageSessionPreLegitimated"
error_code_names[18] = "ServiceIgnored"
error_code_names[19] = "WarningServiceExecutedWithPartialError"
error_code_names[21] = "ServiceSubscriptionTooManyNotifies"
error_code_names[22] = "ServiceSessionDelegitimated"
error_code_names[23] = "EndOfFile"
error_code_names[24] = "ServiceSubscriptionDisabled"
error_code_names[25] = "ServiceLegitimatedForLevel2"
error_code_names[26] = "ServiceLegitimatedForLevel3"
error_code_names[27] = "ServiceMultiResponsePending"
error_code_names[28] = "Next_Messageblock"
error_code_names[29] = "Object_Skipped"
error_code_names[30] = "WarningDsCannotDistribute"
error_code_names[31] = "WarningDsContainerItemNotFound"
error_code_names[32] = "WarningDsPreconditionMissing"
error_code_names[33] = "ServiceLegitimatedForLevel1"
error_code_names[34] = "WaningServiceTransactionAborted"
error_code_names[35] = "MessageBLOBreallocated"
error_code_names[36] = "MessageDirAlreadyExists"
error_code_names[37] = "MessageTemporarilyOutOfResources"
error_code_names[38] = "MessageLegitimLevelCurrentlyDisabled"
error_code_names[39] = "RescheduleHandler"
error_code_names[40] = "BlobEndReached"
error_code_names[41] = "WarningSingleES"
error_code_names[42] = "WarningMultiES"
error_code_names[43] = "WarningMultiESwithSWToken"
error_code_names[207] = "CompClassAssociationEnd"
error_code_names[208] = "CompClassComposition"
error_code_names[209] = "CompStructVariableType"
error_code_names[212] = "CompMetaTypesClass"
error_code_names[218] = "CompRootTypes"
error_code_names[219] = "CompTypesMetaTypes"
generic_error_code_names = {}
generic_error_code_names[0] = "Ok"
generic_error_code_names[1] = "General"
generic_error_code_names[2] = "ApplicationError"
generic_error_code_names[3] = "AccessDenied"
generic_error_code_names[4] = "CantActivate"
generic_error_code_names[5] = "CardinalityOverflow"
generic_error_code_names[6] = "CardinalityUnderflow"
generic_error_code_names[7] = "ClassNotAllowed"
generic_error_code_names[8] = "InvalidAttributeIdentifier"
generic_error_code_names[9] = "InvalidDatatype"
generic_error_code_names[10] = "InvalidObjectIdentifier"
generic_error_code_names[11] = "InvalidPlacement"
generic_error_code_names[12] = "InvalidQualifier"
generic_error_code_names[13] = "InvalidRange"
generic_error_code_names[14] = "InvalidSession"
generic_error_code_names[15] = "NotLinked"
generic_error_code_names[16] = "ServiceTimeout"
generic_error_code_names[17] = "Disconnected"
generic_error_code_names[18] = "FailedToDisconnect"
generic_error_code_names[19] = "InvalidAddress"
generic_error_code_names[20] = "ServiceNotAllowed"
generic_error_code_names[21] = "ServiceNotConnected"
generic_error_code_names[22] = "NotOwner"
generic_error_code_names[23] = "TooManyRequests"
generic_error_code_names[24] = "TooManySessions"
generic_error_code_names[25] = "SessionDelegitimated"
generic_error_code_names[26] = "UnknownService"
generic_error_code_names[27] = "InvalidStorageFormat"
generic_error_code_names[28] = "InvalidComFormat"
generic_error_code_names[29] = "NotChangableInRun"
generic_error_code_names[30] = "WrongNrOfArgumentsOfInvoke"
generic_error_code_names[31] = "WrongArgumentFormatOfInvoke"
generic_error_code_names[32] = "InvokeFailed"
generic_error_code_names[33] = "ObjectCannotBeStoredTwoTimesInParallel"
generic_error_code_names[34] = "ObjectIsLocked"
generic_error_code_names[35] = "StoreInactive"
generic_error_code_names[36] = "HierarchyOverflow"
generic_error_code_names[37] = "ObjectOrAttributeAlreadyExist"
generic_error_code_names[38] = "NotEnoughMemoryAvailable"
generic_error_code_names[39] = "NoMemoryOnStorage"
generic_error_code_names[40] = "NoStorageDetected"
generic_error_code_names[41] = "InvalidTimestampInTypesafeBlob"
generic_error_code_names[42] = "InvalidFileName"
generic_error_code_names[43] = "InvalidArgumentValue"
generic_error_code_names[44] = "StoreDirectoryAlreadyUsed"
generic_error_code_names[45] = "GeneralStoreError"
generic_error_code_names[46] = "InvalidObjectReference"
generic_error_code_names[47] = "GeneralCreate"
generic_error_code_names[48] = "GeneralAddObject"
generic_error_code_names[49] = "GeneralDeleteObject"
generic_error_code_names[50] = "GeneralGetVariable"
generic_error_code_names[51] = "GeneralSetVariable"
generic_error_code_names[52] = "GeneralGetVariableSubrange"
generic_error_code_names[53] = "GeneralSetVariableSubrange"
generic_error_code_names[54] = "GeneralGetMultiVariables"
generic_error_code_names[55] = "GeneralSetMultiVariables"
generic_error_code_names[56] = "GeneralAddLink"
generic_error_code_names[57] = "GeneralRemoveLink"
generic_error_code_names[58] = "InvalidID"
generic_error_code_names[59] = "GeneralComError"
generic_error_code_names[60] = "NotChangableInErrorState"
generic_error_code_names[61] = "MultiESNotSupported"
generic_error_code_names[62] = "ServiceAborted"
generic_error_code_names[63] = "SourceFileNotExisting"
generic_error_code_names[64] = "InvalidVersion"
generic_error_code_names[65] = "CommFormatDiffersFromStoreFormat"
generic_error_code_names[66] = "GeneralTransaction"
generic_error_code_names[67] = "Distribution"
generic_error_code_names[68] = "GeneralPathNotFound"
generic_error_code_names[69] = "GeneralEndOfFile"
generic_error_code_names[70] = "GeneralFSWriteProtected"
generic_error_code_names[71] = "GeneralFSDiskFull"
generic_error_code_names[72] = "GeneralFSInvalidPathName"
generic_error_code_names[73] = "WSTRING_not_supported"
generic_error_code_names[74] = "TransactionAborted"
generic_error_code_names[75] = "StoreForceStore"
generic_error_code_names[76] = "GeneralIntegrity"
generic_error_code_names[77] = "MultiESConflict"
generic_error_code_names[78] = "TemporarilyOutOfResources"
generic_error_code_names[79] = "MultiESLimitExceeded"
generic_error_code_names[80] = "MultiESIncompatibleOtherESVersion"
generic_error_code_names[81] = "ConcurrentTransactionRunning"
generic_error_code_names[82] = "SslError"
generic_error_code_names[83] = "RHPlcProxyTreeUnknown"
generic_error_code_names[84] = "RHPlcProxyTreeNonRedundant"
generic_error_code_names[85] = "ServiceNotAvailable"
generic_error_code_names[86] = "TLSError"

def processTokenGroup(group):
    if not group:
        return

    iterator = group.iterator()
    if iterator.hasNext():
        token = iterator.next()
        if isinstance(token, ClangFuncNameToken):
            if token.getText() == "TD_maybe_report_trace":
                # These cause a lot of false positives.
                return
    
    for node in group.iterator():
        if isinstance(node, ClangTokenGroup):
            processTokenGroup(node)
        elif isinstance(node, ClangVariableToken):
            if node.getSyntaxType() == ClangToken.CONST_COLOR:
                text = node.getText()
                if "0x" in text:
                    try:
                        int_value = int(text, 16) & 0xffffffffffffffff
                        process_const_value(node, int_value)
                    except ValueError:
                        pass

def process_const_value(node, int_value):
    generic_error_code = (int_value & 0x00007f0000000000) >> 40
    error_code = int_value & 0x000000000000ffff
    if error_code & 0x8000:
        error_code -= 0x10000
    omsline = (int_value & 0x00000000ffff0000) >> 16
    if generic_error_code == 0 or error_code == 0 or omsline == 0:
        return

    if int_value & 0x8000000000000000 == 0:
        # I don't know if this is always correct, but it improves results.
        return

    generic_error_code_name = generic_error_code_names.get(generic_error_code)
    if generic_error_code_name is None:
        return

    error_code_name = error_code_names.get(error_code)
    if error_code_name is None:
        return

    SetCommentCmd.createComment(getCurrentProgram(), node.getMinAddress(), "OMS Error: " + generic_error_code_name + "/" + error_code_name, CodeUnit.PRE_COMMENT)

    log = str(node.getMinAddress()) + ": " + hex(int_value) + " => " + generic_error_code_name + "/" + error_code_name
    print(log)


# Set up the DecompInterface
decomp_interface = DecompInterface()

# Get the current program
program = getCurrentProgram()

# Set up the DecompInterface for the current program
decomp_interface.openProgram(program)

counter = 0
for function in program.getFunctionManager().getFunctions(True):
    counter += 1
    if counter % 100 == 0:
        print(str(counter) + " out of " + str(program.getFunctionManager().getFunctionCount()))

    results = decomp_interface.decompileFunction(function, 5, None)
    markup = results.getCCodeMarkup()

    processTokenGroup(markup)
    